### ISSUE TITLE
Incompatible with Node

### ISSUE THREAD

**Issue by TerjeNorderhaug** [ptaoussanis/encore#21]
There is no js/window defined in Nodejs. Sente 1.8.0 requires Encore, making Node fail with:

```
let [loc* (.-location js/window)
             ^
ReferenceError: window is not defined
       at taoensso$encore$get_window_location
```

**Comment by ptaoussanis** [comment]
Hi Terje, thanks for the report.

Just pushed `[com.taoensso/encore "2.39.0"]` which should fix the particular issue with encore, but not certain how this'll impact your ability to use Sente since Sente itself uses `js/window` in a number of places.

@theasp Hi Andrew, could I possibly ping you for feedback on this? Don't use Node myself so not sure what the situation is. I'm assuming you've managed to run Sente on Node despite the use of js/window, yes?

**Comment by TerjeNorderhaug** [comment]
Thanks. I'm still working on getting Sente to work on Nodejs.

**Comment by theasp** [comment]
@TerjeNorderhaug, are you using node as a client or server?

**Comment by TerjeNorderhaug** [comment]
I am using node primarily as a server, with most code shared with the browser app (what some refer to as 'isomorphic').

**Comment by ptaoussanis** [comment]
Closing here to continue the discussion at https://github.com/ptaoussanis/sente/issues/209
