### ISSUE TITLE
Something in encore 2.79.1 (used by timbre) causes large spike in CPU usage

### ISSUE THREAD

**Issue by daveyarwood** [ptaoussanis/encore#33]
Hi Peter,

I'm hoping you might have some insight on a major problem we're having with Alda, which relies on timbre for logging: https://github.com/alda-lang/alda/issues/266  In testing, I believe some part of encore may be the culprit.

To summarize: we are forking 4 worker processes upon startup of an Alda server. For about 10-15 seconds during startup, we're seeing the CPU usage of all 4 worker processes spike dramatically (~150-200% CPU on my 2014 Macbook), before decreasing down to about 2-3% and staying there.

The problem is difficult to profile mostly because I'm bad at profiling 😅  (I fumbled with `jvisualvm` and couldn't find an answer), but also because the CPU spike occurs only briefly while the Alda worker processes are starting up -- it's not like the CPU is just staying elevated and I can grab the top CPU consuming thread from the thread dump and see what it is.

So, in lieu of proper profiling, I've started experimenting with commenting out code and observing the CPU usage.

I was able to put together this base case which shows that requiring the `taoensso.encore` namespace causes the spike: https://github.com/alda-lang/alda/blob/233d95e0da68d2a1003a1bb7c9f249d18b8e885c/server/src/alda/worker.clj 

Requiring other namespaces does not have the same effect.

I spent an hour or two building encore locally and commenting out large chunks of it to see if I could find a particular part of encore that may be responsible for devouring CPU, but didn't have much success there. One thing I noticed is that [requiring `clojure.tools.reader.edn`](https://github.com/ptaoussanis/encore/blob/v2.79.1/src/taoensso/encore.cljx#L48) appears to cause a significant spike in CPU, but it also seems that there might be other causes of heavy CPU usage in `taoensso.encore` -- I tried removing `clojure.tools.reader.edn` from the equation and was still seeing spikes.

I'm at my wit's end here... any help is appreciated!

**Comment by ptaoussanis** [comment]
Hi Dave!

I'm sorry to give you the response I'm sure you were hoping to avoid- but sounds like this really does just need some profiling. Could honestly be _so many_ different things, and it's impossible to say with only the info provided here.

To clarify: there's nothing specifically in Encore that'd I'd expect would cause any particular problem - and it's not an issue I've ever observed myself. Not familiar with your application though, or what it might be doing. I'd note that Encore is a fairly large namespace (~3k loc) - so that's possibly causing a problem if you're using some buggy tooling that's doing work on required namespaces? Are you maybe preprocessing namespaces or something?

On a more general note: while significant spiking on load shouldn't happen, is there a particular reason that it's actually a problem? Is the transient spike causing an ongoing issue? I ask, because that might also help identify/rule-out possible problems.

Otherwise have my hands very full atm, so must regretfully say that I won't be able to do much digging from my end - am sorry.

Perhaps you could try find another profiling tool that's more comfortable to use? Not familiar with jvisualvm, but YourKit isn't too bad to get started with.

Best of luck, hope you find the solution soon!

**Comment by daveyarwood** [comment]
Thanks for all these questions, I think they could take me in the right direction toward finding a fix. I did notice that the CPU spike is a lot smaller when only starting one worker process -- around 30-40%, which seems more reasonable. So the issue is likely something about the way we are spawning multiple child processes at the same time from the main application. I think staggering the spawning of the processes will probably work as a workaround.

I am curious what's causing so much CPU usage, though... I'll give YourKit a try and let you know if I find anything!

**Comment by ptaoussanis** [comment]
Sorry if this was already addressed, haven't had an opportunity to look over all the context for issue: are you actually starting up additional JVM processes? Simultaneously trying to start 4 full JVMs all running Clojure could certainly bring mid-level hardware to its knees.

Depending on the JVM config (esp. wrt memory) - that could also conceivably tank system performance even after the initial loading.

Is it possible you're just seeing the impact of normal JVM+Clojure+compiling, multiplied by your process count?

**Comment by daveyarwood** [comment]
Yes, these are actually separate processes running in separate JVMs. I think you're right -- what we're seeing could very well just be what happens when you start 4 Clojure processes at the same time.

The good news is that I don't think we necessarily have to start them at exactly the same time, and I'm also considering lowering the default number of workers to 2, which ought to be a lot more manageable.

I'll close this issue -- it doesn't seem encore-specific after all. I tried spacing apart starting the worker processes, and CPU usage was much lower (< 50%). Thanks for your insight!

**Comment by ptaoussanis** [comment]
> I'm also considering lowering the default number of workers to 2, which ought to be a lot more manageable.

Disclaimer: feel free to ignore obvious / irrelevant input below ^^

Not at all familiar with your project or the motivation for forking processes, but would in general try encourage as few JVM processes as possible re: efficiency. Is there any possibility you can get away with threading, or other workarounds for whatever motivated the multiple processes?

Or if you're forced to go the many-process route, would recommend confirming that you've tuned your JVM configs as much as possible for this purpose (i.e. to try minimise memory use, etc.). If too much memory is reserved and your processes start competing for swap space, etc. - you can run into severe performance problem.

Best of luck, cheers!
