### ISSUE TITLE
Clojure 1.11 warning `abs already refers...`

### ISSUE THREAD

**Issue by dharrigan** [ptaoussanis/encore#60]
Hi,

With Clojure 1.11 nearly around the corner, testing has revealed this issue with `taoensso.encore`:

`WARNING: abs already refers to: #'clojure.core/abs in namespace: taoensso.encore, being replaced by: #'taoensso.encore/abs`

Thank you.

-=david=-

**Comment by ptaoussanis** [comment]
Hi David, this has already been addressed in the latest versions of Encore - please see [here](https://github.com/ptaoussanis/encore/issues/59).

**Comment by dharrigan** [comment]
Ah!

Yes, totally right, but I forgot (I just digged a bit deeper there now), that I'm using `tempura` latest version (1.2.1) which still uses an older version of encore.

Could tempura be updated to pull in the latest please?

Thank you.

**Comment by ptaoussanis** [comment]
I always update Encore and other dependencies whenever cutting a new release of a library, but it's not feasible for me to issue new releases of every library each time there's a minor dependency bump. In practice this is only worth the effort if there's a significant security fix.

Otherwise would encourage folks to use something like [lein ancient](https://github.com/xsc/lein-ancient) to monitor their transient dependencies for potential updates.

Encore will always safe to update, so long as you stick to the same major version number. (So 2.x is safe to update to 2.y, 3.x is safe to update to 2.y, etc.).

Some more info re: manually controlling encore version [here](https://github.com/ptaoussanis/encore/blob/master/DEP-CONFLICT.md).

Hope that's of some help, at least!

Will keep this issue open in the meantime for other folks that might run into the same issue.

Cheers :-)

**Comment by ptaoussanis** [comment]
Ah, excuse me- I just noticed that you're asking specifically about upgrading from Encore v2.x to v3.x. That __should__ also be okay, but would require double checking. I'll try take a look this weekend - otherwise you could also try to just [switch](https://github.com/ptaoussanis/encore/blob/master/DEP-CONFLICT.md#step-2-of-3-method-2) to the latest (v3.x) version. If it builds okay, it should be fine - would just recommend double checking your usual unit tests, etc.

**Comment by dharrigan** [comment]
Thank you, will give it a whirl and hope for the best :-)

**Comment by ptaoussanis** [comment]
Just confirming that you should indeed be good-to-go with updating from Encore v2 to latest v3 👍 

The only breaking change was a bump to the minimum Clojure dependency, and an opt-in removal/renaming of some vars (which won't affect you by default).

**Comment by dharrigan** [comment]
Thank you! That is very encouraging news.
