### ISSUE TITLE
`nested-merge` only merges maps

### ISSUE THREAD

**Issue by NoahTheDuke** [ptaoussanis/encore#61]
Hey Peter!

I'm using [timbre](https://github.com/ptaoussanis/timbre) (v5.2.1) and running into an issue where `with-merged-config` doesn't do what I expect. I've traced the potential issue back to `encore/nested-merge`:

```clojure
(encore/nested-merge
  {:allow "*" :deny #{"a" "b"}}
  {:deny #{"c" "d"}})
;=> {:allow "*" :deny #{"d" "c"}}
```

I naively expected that this would result in `{:allow "*" :deny #{"a" "b" "c" "d"}}`. Looking at the code, that was the wrong assumption (only maps are merged instead of deeply merging everything).

Is this a change you're interested in? If not, is there an easy way to achieve this behavior locally?

**Comment by ptaoussanis** [comment]
@NoahTheDuke Hi Noah!

So the current behaviour of Timbre and `nested-merge` are indeed both intentional:

#### `nested-merge`

This is just a nesting version of `clojure.core/merge`, which itself is only intended for maps.

#### `with-merged-config`

The intention for this is just to do "merging" in the `clojure.core/merge` (i.e. map) sense.

Why not _also_ merge other data structures like sets?

1. Most of Timbre's config needs can be handled pretty well with simple map merging.
2. If Timbre tried to also merge other data structures (e.g. sets), you'd run into difficulties if you want to specifically _replace_ a set instead of do a union. Rather than open the door to that complexity for something that'd be rarely useful, Timbre just keeps the merging simple.

>  is there an easy way to achieve this behavior locally?

Sure, Timbre's config is just a regular Clojure map in an atom - so you can use all the standard Clojure utils like `swap!`, `update`, `update-in`, etc.:

```
(def config_ (atom {:allow "*" :deny #{"a" "b"}}))
(swap! config_
  (fn [config]
    (update config :deny
      (fn [?s] (clojure.set/union (or ?s #{}) #{"c" "d"})))))

;; => {:allow "*", :deny #{"d" "a" "b" "c"}}
```

Hope that helps?

**Comment by ptaoussanis** [comment]
Assuming I can close this, but feel free to re-open if you're still having trouble!

**Comment by NoahTheDuke** [comment]
Hey Peter, sorry for the "fire and forget" issue.

I don't think the config object is an atom, at least not that I can see anywhere in the code. Is there something I'm missing here?

I ended up writing a custom `merge-ns-filter` as I was hoping to better pinpoint some of our expected warnings and errors in test code. It's still not ideal as there's places for legit warnings or errors to arise in the same muted namespace, but at the moment it's the best I can do (and I've already spent too much dev time on it instead of my actual job :sob:). Ideally, I would be able to say "this specific log call is skipped in this specific way", but that's really complicated and gestures to us having poor tests (which we do). Hopefully after some hammock time, I'll think of something better.

Here's what I wrote, so anyone else who runs into this can maybe benefit as well.

```clojure
(ns company-ns.test-utils.timbre
  "Utility functions for tests that deal with timbre internals and configuration"
  (:require
   [clojure.set :as set]
   [taoensso.timbre :as log]))

(defn- merge-ns-filter-branch
  [existing-filter new-filter]
  (cond
    ;; discard existing universal filter
    (or (= "*" existing-filter) (= #{"*"} existing-filter)) (recur nil new-filter)
    ;; "*" is a universal filter
    (or (= "*" new-filter) (= #{"*"} new-filter)) #{"*"}
    ;; combine filters
    :else (not-empty (cond-> #{}
                       ;; strings are treated as regexes, so add to set
                       (string? existing-filter) (conj existing-filter)
                       (string? new-filter) (conj new-filter)
                       ;; sets are merged
                       (set? existing-filter) (set/union existing-filter)
                       (set? new-filter) (set/union new-filter)))))

(defn- merge-ns-filter
  [existing-filter new-filter]
  (if-not (map? existing-filter)
    (recur {:allow existing-filter} new-filter)
    (let [merged-allow (merge-ns-filter-branch (:allow existing-filter)
                                               (:allow new-filter))
          merged-deny (merge-ns-filter-branch (:deny existing-filter)
                                              (:deny new-filter))]
      (cond-> existing-filter
        merged-allow (assoc :allow merged-allow)
        merged-deny (assoc :deny merged-deny)))))

(defmacro with-merged-ns-filter
  "Deeply merge the given ns-filter map with the current
  `taoensso.timbre/*config*` ns-filter.

  If existing `ns-filter` is not a map, treats it as existing `:allow` (matches
  timbre). Ignore existing `\"*\"` or `{\"*\"}` filter.

  Otherwise, sets and strings are combined into sets. All other types are
  discarded."
  [ns-filter & body]
  `(let [merged-filter# (#'merge-ns-filter (:ns-filter log/*config*) ~ns-filter)]
     (binding [log/*config* (assoc log/*config* :ns-filter merged-filter#)]
       ~@body)))
```

**Comment by ptaoussanis** [comment]
Hi Noah,

> I don't think the config object is an atom, at least not that I can see anywhere in the code. Is there something I'm missing here?

Apologies, you didn't miss anything - I misspoke. The config is a dynamic var, not an atom.
The semantics are the same though, you'd just need to use `alter-var-root` instead of `swap!`.
Have updated the example in my comment.

> I ended up writing a custom merge-ns-filter as I was hoping to better pinpoint some of our expected warnings and errors in test code.

Ideally you/folks would want to avoid needing custom deep-merging behaviour like this since that's quite a lot of incidental complexity, and is quite likely to be fragile.

I might be able to suggest an alternative approach - but to give more specific input on this, I'd need to first understand better what you're trying to do.

What's the motivation for wanting such general-purpose deep ns-filter spec merging?

> Ideally, I would be able to say "this specific log call is skipped in this specific way"

Could you clarify a bit what you mean by "this specific way"?
You want individual log calls to use different ns-filters?

Would it be possible to explain the (solution-agnostic) high level goal?

**Comment by ptaoussanis** [comment]
Hi Noah, thanks for the detailed explanation - that's helpful 👍

If I understand correctly that:
- You have a large number of tests that will trigger high-level logging
- You want to frequently change the ns-filter depending on the test/s
- You want to frequently change the ns-filter through _composition_ in particular (i.e. merging)
- There's a large number of such unique ns-filter specs

Assuming all of that is right, then I guess your current approach seems reasonable.

The biggest downside is that you'll be fighting against an ns-filter spec API that is designed for ease of manual use, rather than for ease of programmatic composition.

One way you might be able to simplify (and avoid tying yourself too much to external implementation details) is to define your own filtering mechanism as a middleware for your tests. I.e.:

- You run a different timbre config when running your tests
- That config includes a simplified filtering mechanism custom tailored to your needs

Whether this is better or worse than your current approach would depend on how simple the customised filtering mechanism would be. E.g. you might want simpler ns filtering, or filtering by something else entirely.

> The ideal and very bad option is create a global filter atom or var and wrap every timbre call, checking to see if that specific call should happen,

Note that with a custom filtering mechanism, your hands would be free to use whatever filtering would be most appropriate - _without_ necessarily needing to pollute your (non-test) code base.

Timbre middleware can examine all info from a logging call - incl. level, namespace, and all raw arguments.

I can't advise on details, but if you could define simpler logical semantics for when certain logging calls should/not occur during testing - in principle it should be possible to check these conditions with test middleware.

That's necessarily also a big vague, but hopefully might make some sense!

Cheers :-)

**Comment by ptaoussanis** [comment]
Closing this for now, but feel free to re-open if you're still having trouble. Cheers :-)
